name: 🌟 Feature Request
description: Suggest a new feature or improvement.
title: ""
labels: ["enhancement"]
type: "feature"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature. Let’s understand your idea better:

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added or improved?
      placeholder: "Eg., Create a new reports screen to export data to Excel."
    validations:
      required: false
