name: Auto-atribuir criador da issue

on:
  issues:
    types: [opened]

jobs:
  auto_assign_creator:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Atribuir criador à issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueCreator = context.payload.issue.user.login;
            const issueNumber = context.payload.issue.number;

            console.log(`Atribuindo ${issueCreator} à issue #${issueNumber}`);

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: [issueCreator],
            });
