# .github/workflows/set_remaining_to_zero.yml
name: Zerar Remaining ao mover para Done

on:
  project_card:
    types: [moved]

jobs:
  zero_remaining:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica se moveu para Done e zera campo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const card = context.payload.project_card;
            const column = await github.rest.projects.getColumn({
              column_id: card.column_id
            });

            if (column.data.name.toLowerCase() === "done") {
              const issueUrl = card.content_url;
              const issueNumber = issueUrl.split('/').pop();

              // Atualiza o campo "remaining"
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `Remaining: 0`
              });
            }
